target 'ios' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'MaterialComponents', :git => 'https://github.com/material-components/material-components-ios', :branch => 'develop'
  pod 'RxSwift', '6.7.1'
  pod 'RxCocoa', '6.7.1'
  pod 'RxGesture', '~> 4.0.4'
  pod 'shared', :path => '../shared'
end
